# Site Settings
baseurl: ""
url : "https://chels-kim.github.io"

# Blog Settings
theme_settings :
  title : Chelsea Kim
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.png
    username : Chelsea Kim
    description : Master's graduate in Computational Neuroscience.
    education :
      - start : 2014
        end : 2018
        experience : Bachelor's of Science, Joint Major Physiology and Math
      - start : 2018
        end : 2020
        experience : Master's of Science, Physiology
    skills : 
      - skill : MATLAB
        value : 95
      - skill : Python
        value : 80
      - skill : Statistical analysis
        value : 100 # Percent value
        
  # Icons
  icons :
    email:  chelsea.br.kim@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: chels-kim
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: ChelseaBrKim
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
